baseURL: 'http://example.org/'
languageCode: en-us
title: Neoblaze · Build beautiful interfaces with blazing speed.

metaDataFormat: 'yaml'

publishDir: '_site'
build:
  writeStats: true

params:
  current_version: '0.1.0'

  repo: 'https://github.com/htcni/neoblaze'
  cdn:
    css: 'https://somecdn.css'

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ''
    hl_inline: false
    lineAnchors: ''
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    tabWidth: 2
    style: dracula
  goldmark:
    renderer:
      hardWraps: true
