baseURL: 'https://neoblaze.vercel.app/'
languageCode: en-us
title: Neoblaze

metaDataFormat: 'yaml'

publishDir: '_site'
build:
  writeStats: true

disableKinds: ['taxonomy', 'term', 'RSS']

params:
  current_version: '0.1.3'

  subtitle: 'Build beautiful interfaces with blazing speed.'
  description: 'Neoblaze is a modern css framework that helps you build beautiful interfaces with blazing speed.'
  author: 'Nitin Bartwal'
  twitter: 'https://twitter.com/bartwalX'

  repo: 'https://github.com/htcni/neoblaze'
  cdn:
    css: 'https://cdn.jsdelivr.net/npm/neoblaze@0.1.3/dist/css/neoblaze.min.css'

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ''
    hl_inline: false
    lineAnchors: ''
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    tabWidth: 2
    style: dracula
  goldmark:
    renderer:
      hardWraps: true
