name: Report a bug 🐛
description: Tell us about a bug or issue to improve neoblaze.
title: 'Provide a general summary of the issue'
labels: [bug]
assignees: '-'
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have [searched](https://github.com/htcni/neoblaze/issues) for duplicate or closed issues.
          required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: Provide a concise summary of the issue.
    validations:
      required: true
  - type: textarea
    id: current-behaviour
    attributes:
      label: Current Behavior
      description: |
        A concise description of what you're experiencing. If applicable, add screenshots to help explain your problem.
    validations:
      required: true
  - type: textarea
    id: expected-behaviour
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: dropdown
    id: os
    attributes:
      label: What operating system(s) are you seeing the problem on?
      multiple: true
      options:
        - Windows
        - macOS
        - Android
        - iOS
        - Linux
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browser(s) are you seeing the problem on?
      multiple: true
      options:
        - Chrome
        - Safari
        - Firefox
        - Microsoft Edge
        - Opera
  - type: input
    id: version
    attributes:
      label: What version of Neoblaze are you using?
      placeholder: 'e.g., v0.1.0 or v1.0.2'
    validations:
      required: true
  - type: textarea
    attributes:
      label: Anything else?
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!
    validations:
      required: false
